# @package _global_
defaults:
  - hydra
  - agents: develop
  - _self_
  - override /hydra/hydra_logging: disabled
  - override /hydra/job_logging: disabled

engine:
  _target_: backend.engines.blender.Blender
  name: "Blender"
  version: "4.5.3"
  exe: "blender"
  resolution_x: 512
  resolution_y: 512
  num_views: 3
  timeout_s: 60

trellis:
  _target_: backend.utils.trellis.TrellisEngine

logging:
  filename: ${now:%Y-%m-%d}-${now:%H-%M-%S}.log

image_generation:
  seed: 42
